# fly.toml app configuration file generated for chao-bot on 2026-05-19T14:29:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chao-bot"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
